// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ListOfNames: typeof import('./src/components/list-of-names.vue')['default']
    MyCounter: typeof import('./src/components/my-counter.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VApp: typeof import('vuetify/lib')['VApp']
    VAppBar: typeof import('vuetify/lib')['VAppBar']
    VAppBarNavIcon: typeof import('vuetify/lib')['VAppBarNavIcon']
    VBtn: typeof import('vuetify/lib')['VBtn']
    VCard: typeof import('vuetify/lib')['VCard']
    VCardText: typeof import('vuetify/lib')['VCardText']
    VContainer: typeof import('vuetify/lib')['VContainer']
    VIcon: typeof import('vuetify/lib')['VIcon']
    VList: typeof import('vuetify/lib')['VList']
    VListItem: typeof import('vuetify/lib')['VListItem']
    VListItemContent: typeof import('vuetify/lib')['VListItemContent']
    VListItemIcon: typeof import('vuetify/lib')['VListItemIcon']
    VListItemSubtitle: typeof import('vuetify/lib')['VListItemSubtitle']
    VListItemTitle: typeof import('vuetify/lib')['VListItemTitle']
    VMain: typeof import('vuetify/lib')['VMain']
    VNavigationDrawer: typeof import('vuetify/lib')['VNavigationDrawer']
    VToolbarTitle: typeof import('vuetify/lib')['VToolbarTitle']
  }
}
